FROM python:3.13.0

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN pip install -U pip
RUN pip install -U wheel
RUN pip install -U setuptools
RUN pip install uv

# Install python packages (-e . is needed for scripts to recognize alcf/ during imports)
RUN uv pip install --system -e .
RUN uv pip install --system -r /app/alcf/requirements.txt

# Setup database and run application
RUN chmod u+x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
