from app.routers.iri_router import AuthenticatedAdapter
from app.routers.account.models import User
from alcf.config import KEYCLOAK_CLIENT_ID, KEYCLOAK_CLIENT_SECRET, KEYCLOAK_REALM_NAME, SECRET_DEV_KEY
from keycloak import KeycloakOpenID
from fastapi import Depends

# Configure Keycloak client
keycloak_openid = KeycloakOpenID(
    server_url="https://keycloak-internal.alcf.anl.gov",
    client_id=KEYCLOAK_CLIENT_ID,
    realm_name=KEYCLOAK_REALM_NAME,
    client_secret_key=KEYCLOAK_CLIENT_SECRET,
    verify=True
)
config_well_known = keycloak_openid.well_known()


class AlcfAuthenticatedAdapter(AuthenticatedAdapter):

    # Get current user
    async def get_current_user(
        self : "AlcfAuthenticatedAdapter",
        api_key: str,
        ip_address: str = None,
        ) -> str:
        """
            Decode the api_key and return the authenticated user's id.
            This method is not called directly, rather authorized endpoints "depend" on it.
            (https://fastapi.tiangolo.com/tutorial/dependencies/)
        """
    
        # TEMP for DEV
        if api_key.replace("Bearer ", "") == SECRET_DEV_KEY:
            return "bcote"

        # Introspect the access token (which should be generated by Keycloak)
        # TODO: Cache this
        introspection = keycloak_openid.introspect(api_key.replace("Bearer ", ""))
        if not introspection["active"]:
            return None

        # Return username
        return introspection.get("username", None)


    # Get User
    async def get_user(
        self : "AlcfAuthenticatedAdapter",
        user_id: str,
        api_key: str,
        client_ip: str = None
        ) -> User:
        """
            Retrieve additional user information (name, email, etc.) for the given user_id.
        """
        
        # Temporary - allow specific username
        if user_id == "bcote":
            return User(id="bcote", name="Benoit Cote", api_key=api_key.replace("Bearer ", ""), client_ip=client_ip)
        elif user_id == "richp":
            return User(id="bcote", name="Paul Rich", api_key=api_key.replace("Bearer ", ""), client_ip=client_ip)
        else:
            return None
